### ISSUE TITLE
Tables on the Sortie page are illegible

### ISSUE THREAD

**Issue by posimagi** [posimagi/bg-wiki-dark-mode#1]
https://www.bg-wiki.com/ffxi/Category:Sortie#Ground_Floor

![image](https://user-images.githubusercontent.com/1747598/211221837-2e82dc28-3439-4fae-8608-b87590718165.png)

**Comment by posimagi** [comment]
Using CSS classes, we can solve this issue for this and many other types of tables. The stylesheet should look something like this:

```css
table.sortie {
    background: #310047;
}
table.sortie .title {
    color: #e2a3ff;
}
table.sortie .header {
    background: #BD77DB;
    color: #000;
}
table.sortie .header th {
    padding: 0.2em;
}
table.sortie tr:nth-child(odd):not(:first-child) {
    background: #272727;
}
table.sortie tr:nth-child(even):not(:nth-child(2)) {
    background: #171717;
}
table.sortie td {
    padding: 0.2em;
}
```

This results in the following output:

![image](https://user-images.githubusercontent.com/1747598/218068387-b06282fb-a3ff-4be0-9ce2-f9a9b005c829.png)
